#167891576 As a user, I can log into the Barefoot Nomad application via email & password
andela/banshee-bn-backend pull request #16
Opened 2019-08-21 05:34 UTC by Pomile

#### What does this PR do?
Have a user login
#### Description of Task to be completed?
- Write test for login
- Create login validator
- Create login service
- Create login route handler
- Modify travis
- Install bcrypt
#### How should this be manually tested?
1. clone the project
2. cd to the project directory
3. Run `npm install`
4. Run `npm run migrate`
5. Run `npm run seed`
6. Run `npm test`

#### What are the relevant pivotal tracker stories?
[#167891576](https://www.pivotaltracker.com/story/show/167891576)
#### Any background context you want to add?
Nil
#### Screenshots
Nil

2019-08-21 12:58 UTC, femitj commented on src/controllers/auth.js
> +  static async login(req, res) {
change the file-name to Auth.js

2019-08-21 13:01 UTC, femitj reviewed
can you move your login unit test into a folder called auth.test.js

2019-08-21 14:13 UTC, meetKazuki commented on src/controllers/auth.js
> +    const { email, password, companyId } = req.body;
Do we need `companyId` for login also?

2019-08-22 04:00 UTC, Pomile commented on src/controllers/auth.js
> +    const { email, password, companyId } = req.body;
Yes

2019-08-22 19:32 UTC, tvpeter commented on src/controllers/Auth.js
> +        const payload = user;
I kind of think the payload is too big, we can select just properties like userid, name and companyId to save in the token

2019-08-22 19:44 UTC, tvpeter reviewed
Nice work. Kindly check my below comment.

2019-08-22 19:52 UTC, tvpeter reviewed
I just saw the `Token` helper class that you can even use.

2019-08-22 19:57 UTC, Pomile commented
> I just saw the `Token` helper class that you can even use.

Thank you Peter,
I am aware that Tijani created Jwt helper which i will latter use when i rebase to the latest branch.

2019-08-23 08:03 UTC, sneakymaxy commented on src/controllers/Auth.js
> +    const { email, password, companyId } = req.body;
Please could you clarify why ```companyId``` is necessary for login

2019-08-26 11:44 UTC, meetKazuki commented on test/auth.test.js
> +    describe('User Login', () => {
Check this indentation issue

2019-08-26 12:54 UTC, thatkazuk1 approved these changes

2019-08-26 13:08 UTC, max-wel requested changes

2019-08-26 13:08 UTC, sneakymaxy commented on src/database/models/user.js
> -    User.belongsTo(models.Company, {
Why did you delete this

2019-08-26 13:08 UTC, max-wel approved these changes

2019-08-27 10:46 UTC, daniellamarr approved these changes
Good to go!

2019-08-27 10:46 UTC, merged