Chore: Setup postgresl database
andela/banshee-bn-backend pull request #2
Opened 2019-08-15 10:12 UTC by femitj

#### What does this PR do?
This PR setup PostgreSQL database

#### Description of Task to be completed?
 * Setup express server
 * Setup babel 
 * Setup Postgres

#### How should this be manually tested?
Clone this repo https://github.com/andela/banshee-bn-backend into any folder of your choice.
Cd into the clone folder
Initialize npm by running npm init
Run npm run start:dev

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[https://www.pivotaltracker.com/story/show/167891561](url)

#### Screenshots
N/A

#### Questions:
N/A

2019-08-15 10:36 UTC, Pomile reviewed
I noticed you used session in the app(index.js - server entry point). I don't think we need to use session in this regard since we are using json web token.

2019-08-15 10:41 UTC, femitj commented
Yes you're right @Pomile, i did not include that myself as it was already in the repo

2019-08-15 10:45 UTC, meetKazuki commented
1. Where you asked for *relevant pivotal stories*, I believe the right thing is to insert the PT ID instead of providing a link as you did.
2. `body-parser` middleware is also unnecessary at this point:
``` js
app.use(express.json());
app.use(express.urlencoded({ extended: false });
```
will suffice here

####
_I also made some changes to  `index.js` so I don't know how we can resolve the conflict that will arise_

2019-08-15 10:46 UTC, meetKazuki commented
> Yes you're right @Pomile, i did not include that myself as it was already in the repo

Concerning this, you can start with a barebone template and then add things as necessary in the future

2019-08-15 10:47 UTC, Pomile commented
Ok. Cool

2019-08-15 10:48 UTC, femitj commented
okay thanks @meetKazuki, I've taken note of that

2019-08-15 10:51 UTC, meetKazuki commented
> okay thanks @meetKazuki, I've taken note of that

Also include the PT ID in the title of PR. Something like this `<PT ID> Setup PostgreSQL Database`

2019-08-15 11:11 UTC, Pomile approved these changes

2019-08-15 11:16 UTC, thatkazuk1 requested changes
Have you implemented said changes @femitj?

2019-08-15 11:19 UTC, femitj commented
> Have you implemented said changes @femitj?

pls refer to the changes you requested?

2019-08-16 04:49 UTC, tvpeter commented on src/index.js
> +app.use(express.static(__dirname + '/public'));
Do we need static files directory? I don't think so since it's an api

2019-08-16 04:51 UTC, tvpeter commented on src/index.js
> +  session({
We might not need sessions.

2019-08-16 04:55 UTC, tvpeter reviewed
Kindly remove the sessions and static files directory. Thank you

2019-08-16 10:42 UTC, closed without merging