#167891583 Implements Multi-City Trip Request
andela/banshee-bn-backend pull request #39
Opened 2019-09-04 00:49 UTC by meetKazuki

#### What does this PR do?
* implements multi-city trip request

#### Description of Task to be completed?
* complete implementation of feature
* write tests
* document using swagger

#### How should this manually be Tested?

#### What are the relevant Pivotal Tracker stories?
[#167891583](https://www.pivotaltracker.com/story/show/167891583)

#### Screenshots (if appropriate)

2019-09-06 08:32 UTC, femitj approved these changes

2019-09-09 07:19 UTC, max-wel approved these changes
Good job

2019-09-09 09:07 UTC, daniellamarr requested changes
Kindly refactor your implementation to sync with the scope of the product

2019-09-09 09:58 UTC, daniellamarr approved these changes

2019-09-09 09:58 UTC, merged